### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fale** [casperdcl/git-fame#3]
If I try to run gitfame on the github.com/ansible/ansible repo:

The following output appears:
```
Blame:   4%|█████▌                                                                                                                                          | 126/3265 [00:12<09:12,  5.68it/s]Traceback (most recent call last):
  File "/usr/bin/gitfame", line 9, in <module>
    load_entry_point('git-fame==1.1.0', 'console_scripts', 'gitfame')()
  File "/usr/lib/python3.5/site-packages/gitfame/_gitfame.py", line 239, in main
    run(args)
  File "/usr/lib/python3.5/site-packages/gitfame/_gitfame.py", line 181, in run
    auths = RE_AUTHS.findall(blame_out)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by casperdcl** [comment]
Hmm...

``` sh
$ git clone git@github.com:ansible/ansible
$ cd ansible
ansible (devel)$ git fame
Blame: 100%|████████████████████████████████| 3265/3265 [03:01<00:00, 18.01it/s]
```

Though I get a different error later related to unicode (on python 2.7). Probably due to unicode characters in author names. I thought I had fixed that. Grr.

**Comment by Fale** [comment]
Actually, I used the python3 version. It could be the same problem that appears in different ways on py2 and py3?
