### ISSUE TITLE
tqdm._tqdm.TqdmKeyError: "Unknown argument(s): {'lock_args': (False,)}"

### ISSUE THREAD

**Issue by MartinThoma** [casperdcl/git-fame#42]
```
$ git fame --cost hour,month                                                                                                                                                  
Traceback (most recent call last):
  File "/home/math/.pyenv/versions/3.8.1/bin/git-fame", line 8, in <module>
    sys.exit(main())
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/gitfame/_gitfame.py", line 422, in main
    run(args)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/gitfame/_gitfame.py", line 370, in run
    for res in mapper(statter, gitdirs):
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/gitfame/_gitfame.py", line 231, in _get_auth_stats
    for fname in tqdm(file_list, desc=gitdir if prefix_gitdir else "Processing",
  File "/home/math/.local/lib/python3.8/site-packages/tqdm/_tqdm.py", line 855, in __init__
    raise (TqdmDeprecationWarning(dedent("""\
tqdm._tqdm.TqdmKeyError: "Unknown argument(s): {'lock_args': (False,)}"
```

* Python 3.8.1
* git-fame==1.12.1
* tqdm==4.32.2

**Comment by MartinThoma** [comment]
Works with `tqdm-4.47.0`

**Comment by casperdcl** [comment]
yes should have a better warning. Needs `tqdm>=4.38.0`.

**Comment by MartinThoma** [comment]
I would put it as a dependency in the setup.py: https://github.com/casperdcl/git-fame/blob/master/setup.py#L66

Should I create a PR?

**Comment by casperdcl** [comment]
actually it's better to go for `>=4.42.0` for better concurrent multi-repo support but there are other issues with this dependency. Will fix in a few min.

**Comment by MartinThoma** [comment]
Wow, you're fast! Thank you for fixing it!
